commit after tag

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -20,17 +20,20 @@ jobs:
       - name: Get previous commit SHA
         id: get_previous_commit
         run: |
-          echo "BEFORE commit is ${{ github.event.before }}"
-          echo "previous_commit=${{ github.event.before }}" >> "$GITHUB_ENV"
+          LATEST_TAG=$(git describe --tags --abbrev=0)
+          if [[ -z "$LATEST_TAG" ]]; then
+            echo "No tag found. Failing..."
+            exit 1
+          fi
+          echo "latest_tag=${LATEST_TAG#v}" >> "$GITHUB_ENV" # Remove 'v' prefix from the tag
 
       - name: Check if version changed and is greater than the previous
         id: version_check
         run: |
           # Compare the current version with the version from the previous commit
-          PREVIOUS_NPM_VERSION=$(git show ${{ env.previous_commit }}:package.json | jq -r '.version')
+          PREVIOUS_NPM_VERSION=${{ env.latest_tag }}
           CURRENT_NPM_VERSION=$(jq -r '.version' package.json)
           CURRENT_CARGO_VERSION=$(awk -F '"' '/^version/ {print $2}' Cargo.toml)
-          echo "PREVIOUS_NPM_VERSION: $PREVIOUS_NPM_VERSION"
           echo "CURRENT_NPM_VERSION: $CURRENT_NPM_VERSION"
           echo "CURRENT_CARGO_VERSION: $CURRENT_CARGO_VERSION"
           if [[ "$CURRENT_NPM_VERSION" != "$CURRENT_CARGO_VERSION" ]]; then # Cargo.toml and package.json versions must match
